# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Back CI

permissions:
  id-token: write
  contents: read
  checks: write

defaults: 
  run:
    working-directory: back

on:
  push:
    branches: [ "master" ]
    paths: [ "back/**" ]
  pull_request:
    branches: [ "master" ]
    paths: [ "back/**" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3
      with:
        directory: back
    - name: publish tests results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        working-directory: back
        name: Tests report
        path: './target/surefire-reports/*.xml'
        reporter: java-junit
